"""Render a ScanResult (+ optional agent analysis) into Markdown or JSON reports."""
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from apimapper.core.models import ScanResult


def to_json(scan: ScanResult, agent_analysis: dict | None = None) -> str:
    data = {
        "summary": scan.summary(),
        "scope_engagement": scan.scope_engagement,
        "target": scan.target,
        "target_type": scan.target_type,
        "started_at": scan.started_at,
        "finished_at": scan.finished_at,
        "endpoints": [
            {**asdict(e), "source": e.source.value, "full_url": e.full_url, "fingerprint": e.fingerprint}
            for e in scan.endpoints
        ],
        "secrets": [{**asdict(s), "source": s.source.value, "severity": s.severity.value} for s in scan.secrets],
        "errors": scan.errors,
        "agent_analysis": agent_analysis,
    }
    return json.dumps(data, indent=2, default=str)


def to_markdown(scan: ScanResult, agent_analysis: dict | None = None) -> str:
    s = scan.summary()
    lines = [
        f"# API Mapping Report — {scan.target}",
        "",
        f"**Engagement:** {scan.scope_engagement or 'N/A'}  ",
        f"**Target type:** {scan.target_type}  ",
        f"**Scan window:** {scan.started_at} → {scan.finished_at or 'in progress'}",
        "",
        "## Summary",
        "",
        f"- Endpoints discovered: **{s['total_endpoints']}**",
        f"- Probed (in-scope): **{s['in_scope_probed']}**",
        f"- Discovered but out of scope (not probed): **{s['out_of_scope_discovered']}**",
        f"- Secrets found: **{s['total_secrets']}** ({s['secrets_validated_live']} confirmed live)",
        "",
    ]

    if agent_analysis:
        lines += ["## Executive Summary", "", agent_analysis.get("executive_summary", ""), ""]

        if agent_analysis.get("priority_findings"):
            lines += ["## Priority Findings", ""]
            for pf in agent_analysis["priority_findings"]:
                lines.append(
                    f"- **[{pf.get('severity', 'info').upper()}]** "
                    f"`{pf.get('fingerprint_or_type', '')}` — {pf.get('reasoning', '')}\n"
                    f"  - Next step: {pf.get('recommended_next_step', '')}"
                )
            lines.append("")

        if agent_analysis.get("endpoint_clusters"):
            lines += ["## Endpoint Clusters", ""]
            for c in agent_analysis["endpoint_clusters"]:
                lines.append(f"### {c.get('cluster_name', 'Unnamed cluster')}")
                lines.append(f"Pattern: `{c.get('pattern', '')}`  ")
                lines.append(f"{c.get('summary', '')}")
                lines.append("")

    lines += ["## Secrets Found", ""]
    if scan.secrets:
        lines.append("| Type | Redacted Value | Severity | Live? | Source |")
        lines.append("|---|---|---|---|---|")
        for sec in scan.secrets:
            live = "✅" if sec.validated_live else ("❌" if sec.validated_live is False else "—")
            lines.append(
                f"| {sec.secret_type} | `{sec.value_redacted}` | {sec.severity.value} | {live} | {Path(sec.source_file).name} |"
            )
    else:
        lines.append("_None found._")
    lines.append("")

    lines += ["## All Endpoints", ""]
    lines.append("| Path | Host | In Scope | Probed | Status | Tags |")
    lines.append("|---|---|---|---|---|---|")
    for e in scan.endpoints:
        scope_marker = "✅" if e.in_scope else ("❌" if e.in_scope is False else "?")
        lines.append(
            f"| `{e.path}` | {e.base_host or '—'} | {scope_marker} | "
            f"{'yes' if e.probed else 'no'} | {e.status_code or '—'} | {', '.join(e.tags) or '—'} |"
        )
    lines.append("")

    if scan.errors:
        lines += ["## Notes / Errors", ""] + [f"- {err}" for err in scan.errors] + [""]

    lines += [
        "---",
        "_Generated by apimapper. Active probing, if performed, was restricted to hosts "
        "explicitly listed in scope.yaml and limited to non-destructive liveness/header checks._",
    ]

    return "\n".join(lines)


def write_report(scan: ScanResult, out_path: str | Path, agent_analysis: dict | None = None) -> Path:
    out_path = Path(out_path)
    if out_path.suffix == ".json":
        out_path.write_text(to_json(scan, agent_analysis))
    else:
        out_path.write_text(to_markdown(scan, agent_analysis))
    return out_path
